apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanpatternwithcloudnative-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanpatternwithcloudnative-api
  template:
    metadata:
      labels:
        app: cleanpatternwithcloudnative-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "cleanpatternwithcloudnative"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: cleanpatternwithcloudnative-api
        image: spicycoder/cleanpatternwithcloudnative:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://aspire-dashboard-service:18889"
        - name: OTEL_SERVICE_NAME
          value: "CleanPatternWithCloudNative.Api"
        - name: ConnectionStrings__redis
          value: redis-master:6379
        - name: ConnectionStrings__cleanpatternwithcloudnativedb
          value: "Host=postgres-postgresql;Port=5432;Database=cleanpatternwithcloudnativedb;Username=postgres;Password=postgres;"